services:
#RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"     # AMQP-Port
      - "15672:15672"   # Management-UI
    networks:
      - finance_net
#Publisher Service
  publisher:
    image: arnel95/stock-publisher:latest
    container_name: stock-publisher
    # RabbitMQ URL via Umgebungsvariable
    environment:
      - RABBITMQ_URL=amqp://admin:password@rabbitmq:5672/
    depends_on:
      - rabbitmq
    networks:
      - finance_net
# Mongo Datebanken Service
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - "27017:27017"
    networks:
      - finance_net
    volumes:
      - ./data/mongo1:/data/db

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - "27018:27017"
    networks:
      - finance_net
    volumes:
      - ./data/mongo2:/data/db

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - "27019:27017"
    networks:
      - finance_net
    volumes:
      - ./data/mongo3:/data/db

#Frontend Services
  frontend1:
    image: arnel95/stock-liveview:latest
    container_name: frontend1
    environment:
      - MONGO_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/stockmarket?replicaSet=rs0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - finance_net

  frontend2:
    image: arnel95/stock-liveview:latest
    container_name: frontend2
    environment:
      - MONGO_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/stockmarket?replicaSet=rs0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - finance_net

#Nginx Load Balancer
  loadbalancer:
    image: nginx:alpine
    container_name: loadbalancer
    depends_on:
      - frontend1
      - frontend2
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - finance_net

#Consumer
  consumer-aapl:
    image: arnel95/stock-consumer:latest
    container_name: consumer-aapl
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=AAPL
      - MONGODB_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/stockmarket?replicaSet=rs0
    depends_on:
      - rabbitmq
      - mongo1
      - mongo2
      - mongo3
    networks:
      - finance_net

  consumer-msft:
    image: arnel95/stock-consumer:latest
    container_name: consumer-msft
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=MSFT
      - MONGODB_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/stockmarket?replicaSet=rs0
    depends_on:
      - rabbitmq
      - mongo1
      - mongo2
      - mongo3
    networks:
      - finance_net

  consumer-tsla:
    image: arnel95/stock-consumer:latest
    container_name: consumer-tsla
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - RABBITMQ_QUEUE=TSLA
      - MONGODB_URL=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/stockmarket?replicaSet=rs0
    depends_on:
      - rabbitmq
      - mongo1
      - mongo2
      - mongo3
    networks:
      - finance_net
networks:
  finance_net:
    driver: bridge